/** Domain state */
export function createSlice() {
    return {
        tasks: [],
        weeklyScores: [0, 0, 0, 0, 0, 0, 0],
        dailyHistory: {},
        currentDecomposedPlan: null,
        activeCategoryFilter: 'all',
        deferredInstallPrompt: null,
        editingTaskId: null,
        trackedFocusByDay: {},
        enterpriseSyncSuppress: false,
        userProfile: {
            name: '使用者',
            role: '知識工作者',
            streak: 0,
            bestStreak: 0,
            joinDay: 1,
            workStart: '09:00',
            workEnd: '18:00',
            peakStart: '09:00',
            peakEnd: '12:30',
            streakThreshold: 80,
            enableConfetti: true,
            apiEnabled: false,
            apiMode: 'direct',
            apiModel: 'deepseek-chat',
            apiProxyUrl: 'http://localhost:3001/api/chat',
            enterpriseApiUrl: 'http://localhost:3001'
        },
        enterpriseSession: null,
        enterpriseGroupData: null,
        teamNotifications: [],
        chatHistory: [],
        coachAgentMessages: [],
        coachRequestInFlight: false,
        ragServiceActive: false,
        ragRetrievalMode: 'hybrid',
        ragSyncedGroupKey: null,
        checkedRagKbs: ['general'],
        rolledCountOnInit: 0,
        todayFocusTaskId: null,
        focusSession: null,
        enterpriseSyncQueue: [],
        schedulerTabPending: null,
        onboardingStep: 0,
        selectedDocFile: null
    };
}